branch-defaults:
  prod:
    environment: TradingpostApi-Docker-Env
    group_suffix: null
  uat:
    environment: UAT2-TradingpostApi-Docker-Env
global:
  application_name: Tradingpost-Api-Docker
  branch: null
  default_ec2_keyname: beanstalk-production-key
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
