service: tradingpost-job
app: tradingpost-app

frameworkVersion: '3'

plugins:
  - serverless-webpack

provider:
  stage: production
  name: aws
  tags:
    service: tradingpost-background-job
  runtime: nodejs16.x
  iam:
    role: arn:aws:iam::670171407375:role/Basic-Lambda-Role
  vpc:
    securityGroupIds:
      - sg-0f6d411d350ce59d4
    subnetIds:
      - subnet-01fa64739811f141b
      - subnet-04943437a165d812b
      - subnet-0365b7b01827b2dfe

functions:
  add-meta-data:
    handler: market-data/add-meta-data.run
    description: Ingests securities, exchanges, in the morning, in the evening it ingests stats, quotes, and closing pricing
    logRetentionInDays: 14
    timeout: 600
    memorySize: 1024
    events:
      - schedule: cron(20 20 ? * MON-FRI *) # 4:20 PM EDT
      - schedule: cron(20 19 ? * MON-FRI *) # 4:20 PM EST
      - schedule: cron(0 12 ? * MON-FRI *) # 8:00 AM EDT
      - schedule: cron(0 11 ? * MON-FRI *) # 8:00 AM EST
  add-holidays:
    handler: market-data/add-holidays.run
    description: Ingests market holidays once a year
    logRetentionInDays: 14
    timeout: 300
    memorySize: 1024
    events:
      - schedule: cron(0 0 1 1 ? *)
  add-security-pricing:
    handler: market-data/add-security-prices.run
    description: Ingests security prices
    logRetentionInDays: 14
    timeout: 120 # TODO: Change to 1 min once I update function body
    memorySize: 1024
    events:
      # Run M-F every-day from 9:00AM ET -> 4:00 ET
      # We run 8:00 -> 4 because of daylight savings -- shift would be 8->3
      # then we just validate within the function that it should ingest
      - schedule: cron(* 12-20 ? * MON-FRI *)

