service: tradingpost-job
app: tradingpost-app

frameworkVersion: '3'

plugins:
  - serverless-prune-plugin
  - serverless-esbuild

package:
  individually: true

custom:
  prune:
    automatic: true
    number: 1
  esbuild:
    platform: node
    target: 'node16'
    bundle: true
    minify: true
    sourcemap: true
    external:
      - '@sparticuz/chromium'
      - 'puppeteer-core'
    exclude:
      - pg-native
  brokerage-queue:
    production: arn:aws:sqs:us-east-1:670171407375:brokerage-task-queue

provider:
  stage: production
  name: aws
  architecture: x86_64
  environment:
    CONFIGURATION_ENV: production
    NODE_ENV: production
  tags:
    service: tradingpost-background-job
  runtime: nodejs16.x
  iam:
    role: arn:aws:iam::670171407375:role/Basic-Lambda-Role
  vpc:
    securityGroupIds:
      - sg-0f6d411d350ce59d4
    subnetIds:
      - subnet-01fa64739811f141b
      - subnet-04943437a165d812b
      - subnet-0365b7b01827b2dfe

functions:
  # ================================ Healthcheck ================================
  healthcheck:
    handler: healthcheck/api.handler
    description: Healthcheck for the Api
    logRetentionInDays: 14
    timeout: 10
    memorySize: 512
    reservedConcurrency: 1
    events:
      - schedule:
          rate: cron(0/1 * * * ? *)
          enabled: true


  # ================================ Notifications ================================

  ###### Send Post Notifications for Watchlists Users Follow & Create
  notification-post-watchlists:
    handler: notifications/post-watchlists.handler
    description: Pulls posts related to watchlist symbols and sends a notification
    logRetentionInDays: 14
    timeout: 900
    memorySize: 2048
    reservedConcurrency: 1
    events:
      - schedule:
          rate: cron(0 13 ? * MON-FRI *) # 8:00 AM EST
          enabled: true
      - schedule:
          rate: cron(0 1 ? * MON-FRI *) # 8:00 PM EST
          enabled: true

  ###### Send Post Notifications for Holdings Users Have(Users have signed-up with a brokerage account)
  notification-post-holdings:
    handler: notifications/post-holdings.handler
    description: Pulls posts related to the holdings that users have when they've signed up with a brokerage account
    logRetentionInDays: 14
    timeout: 900
    memorySize: 2048
    reservedConcurrency: 1
    events:
      - schedule:
          rate: cron(0 13 ? * MON-FRI *) # 8:00 AM EST
          enabled: true
      - schedule:
          rate: cron(0 1 ? * MON-FRI *) # 8:00 PM EST
          enabled: true

  ###### Send notification to user who follows someone who has new trades
  notification-new-trades:
    handler: notifications/new-holdings.handler
    description: Send a notification to a user who follows someone, and that someone has new holds/has made trades
    logRetentionInDays: 14
    timeout: 900
    memorySize: 2048
    reservedConcurrency: 1
    events:
      - schedule:
          rate: cron(0 13 ? * MON-FRI *) # 8:00 AM EST
          enabled: true

  # ================================ Brokerage ================================

  ###### Generate Robinhood Data Collection Tasks
  generate-brokerage-tasks:
    handler: brokerage/generate-brokerage-tasks.run
    description: Generates tasks for brokerage to process
    logRetentionInDays: 14
    timeout: 900
    memorySize: 1024
    reservedConcurrency: 1
    events:
      - schedule:
          rate: cron(0 11 ? * MON-FRI *) # 7:00 AM EDT
          enabled: true
      - schedule:
          rate: cron(0 10 ? * MON-FRI *) # 7:00 AM EST
          enabled: true

  ###### Brokerage Task Runner
  brokerage-task-runner:
    handler: brokerage/task-runner.handler
    description: Runs brokerage tasks that are pushed to SQS queue -- rather than on cadence
    logRetentionInDays: 14
    timeout: 900
    memorySize: 1024
    reservedConcurrency: 1
    events:
      - sqs:
          arn: ${self:custom.brokerage-queue.${opt:stage}}
          batchSize: 1

  # ================================ Market Data ================================

  ###### Add Exchange Holidays
  add-holidays:
    handler: market-data/add-holidays.run
    description: Ingests market holidays once a year
    logRetentionInDays: 14
    timeout: 300
    reservedConcurrency: 1
    memorySize: 1024
    events:
      - schedule:
          rate: cron(0 0 1 1 ? *)
          enabled: true

  ###### Collect End Of Day Pricing for Securities(Reconcile 4pm close price)
  eod-pricing:
    handler: market-data/eod-pricing.run
    description: Ingests pricing for securities after market close & allow for 15min delay to kick in
    logRetentionInDays: 14
    timeout: 600
    reservedConcurrency: 1
    memorySize: 1024
    events:
      - schedule:
          rate: cron(20 19 ? * MON-FRI *) # 4:20 EST
          enabled: true
      - schedule:
          rate: cron(20 20 ? * MON-FRI *) # 4:20 EDT
          enabled: true

  ###### Collect Intraday-Pricing for Securities
  intraday-pricing:
    handler: market-data/intraday-pricing.run
    description: Ingests intraday pricing
    logRetentionInDays: 14
    timeout: 600
    reservedConcurrency: 1
    memorySize: 2048
    events:
      - schedule:
          rate: cron(* 12-20 ? * MON-FRI *)
          enabled: true

  ###### Roll-Forward Yesterday's Prices to Start The Day(if a trading day)
  morning-pricing-forward:
    handler: market-data/morning-pricing-rollover.run
    description: Roll yesterdays is_eod pricing forward, then let our IEX pricing dictate the rest
    logRetentionInDays: 14
    timeout: 300
    reservedConcurrency: 1
    memorySize: 2048
    events:
      - schedule:
          rate: cron(28 13 ? * MON-FRI *)
          enabled: true
      - schedule:
          rate: cron(28 12 ? * MON-FRI *)
          enabled: true

  ###### Update Securities Information(statistics)
  ### Update for stats is every-day at 5am -- which would update the prior day market
  securities-information:
    handler: market-data/securities-information.run
    description: Runs every trading day at 5AM ET and updates securities information
    logRetentionInDays: 14
    timeout: 300
    reservedConcurrency: 1
    memorySize: 2048
    events:
      - schedule:
          rate: cron(0 9 ? * TUES-SAT *)
          enabled: true
      - schedule:
          rate: cron(0 8 ? * TUES-SAT *)
          enabled: true

  ###### Pulls in new securities & data from IEX and pushes new data over to our security table
  ### Pulls every-day at 5am UTC
  securities-update:
    handler: market-data/securities-update.run
    description: Pulls in new securities and data from IEX and pushes new data over ot our security table
    logRetentionInDays: 14
    timeout: 300
    reservedConcurrency: 1
    memorySize: 2048
    events:
      - schedule:
          rate: cron(0 5 * * ? *)
          enabled: true

  ###### Remove old securities
  security-pruning:
    handler: market-data/security-pruning.run
    description: Prunes security data
    reservedConcurrency: 1
    logRetentionInDays: 14
    timeout: 600
    memorySize: 1024
    events:
      - schedule:
          rate: cron(0 7 ? * MON-SAT *)
          enabled: true

  # ================================ Social Media ================================

  ###### Collect Spotify Content
  spotify:
    handler: social-media/spotify.run
    description: Ingests Spotify User Data
    logRetentionInDays: 14
    timeout: 600
    memorySize: 1024
    reservedConcurrency: 1
    events:
      - schedule:
          rate: cron(0 * ? * MON-SUN *) # Run once a day at 7AM ET
          enabled: true
      - schedule:
          rate: cron(0 * ? * MON-SUN *) # Run once a day at 7PM ET
          enabled: true

  ###### Collect Substack Content
  substack:
    handler: social-media/substack.run
    description: Ingests Substack Data
    logRetentionInDays: 14
    timeout: 900
    memorySize: 1600
    reservedConcurrency: 1
    events:
      - schedule:
          rate: cron(0 * ? * MON-SUN *) # Run once a day at 7AM ET
          enabled: true
      - schedule:
          rate: cron(0 * ? * MON-SUN *) # Run once a day at 7PM ET
          enabled: true

  ###### Collect Twitter Content
  twitter:
    handler: social-media/twitter.run
    description: Ingests Twitter Data
    logRetentionInDays: 14
    timeout: 900
    memorySize: 1600
    reservedConcurrency: 1
    events:
      - schedule:
          rate: cron(*/1 * ? * MON-SUN *) # Run every 10 minutes every day
          enabled: true

  ###### Collect YouTube Content
  youtube:
    handler: social-media/youtube.run
    description: Ingests YouTube User Data
    logRetentionInDays: 14
    timeout: 600
    memorySize: 1024
    reservedConcurrency: 1
    events:
      - schedule:
          rate: cron(0 * ? * MON-SUN *) # Run once a day at 7AM ET
          enabled: true
