version: '3.8'
services:
  tradingpost-api-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - CONFIGURATION_ENV=production
      - FINICITY_CALLBACK_URL=https://m.tradingpostapp.com/auth/finicity
    env_file:
      - .env