import { AccountGroupHPRs, AccountGroupHPRsTable, FinicityAccount, FinicityHolding, FinicityInstitution, FinicityTransaction, FinicityUser, GetSecurityBySymbol, GetSecurityPrice, HistoricalHoldings, IBrokerageRepository, ISummaryRepository, SecurityHPRs, SecurityIssue, SecurityPrices, TradingPostAccountGroups, TradingPostAccountGroupStats, TradingPostAccountToAccountGroup, TradingPostBrokerageAccounts, TradingPostBrokerageAccountsTable, TradingPostBrokerageAccountWithFinicity, TradingPostCurrentHoldings, TradingPostCurrentHoldingsTable, TradingPostCurrentHoldingsTableWithSecurity, TradingPostCustomIndustry, TradingPostHistoricalHoldings, TradingPostInstitution, TradingPostInstitutionTable, TradingPostInstitutionWithFinicityInstitutionId, TradingPostTransactions, TradingPostTransactionsTable, TradingPostUser, TradingPostCashSecurity, FinicityAccountAndInstitution, FinicityAndTradingpostBrokerageAccount, OptionContract, OptionContractTable, IbkrAccountTable, IbkrAccount, IbkrSecurity, IbkrActivity, IbkrCashReport, IbkrNav, IbkrPl, IbkrPosition, TradingPostCurrentHoldingsTableWithMostRecentHolding, SecurityTableWithLatestPriceRobinhoodId, TradingPostTransactionsByAccountGroup, BrokerageTask, BrokerageTaskTable, BrokerageTaskStatusType, DirectBrokeragesType, BrokerageTaskType } from "./interfaces";
import { IDatabase, IMain } from "pg-promise";
import { DateTime } from "luxon";
import { addSecurity, getUSExchangeHoliday } from "../market-data/interfaces";
import { OptionContractTableWithRobinhoodId, RobinhoodAccount, RobinhoodAccountTable, RobinhoodInstrument, RobinhoodInstrumentTable, RobinhoodOption, RobinhoodOptionTable, RobinhoodPosition, RobinhoodTransaction, RobinhoodUser, RobinhoodUserTable } from "./robinhood/interfaces";
export default class Repository implements IBrokerageRepository, ISummaryRepository {
    private db;
    private readonly pgp;
    constructor(db: IDatabase<any>, pgp: IMain);
    updateErrorStatusOfAccount: (accountId: number, error: boolean, errorCode: number) => Promise<void>;
    getCashSecurityId: () => Promise<GetSecurityBySymbol>;
    getFinicityAccountByTradingpostBrokerageAccountId: (tpBrokerageAccountId: number) => Promise<FinicityAndTradingpostBrokerageAccount | null>;
    getFinicityAccountByFinicityAccountId: (finicityAccountId: string) => Promise<FinicityAccountAndInstitution>;
    getSecurityPricesWithEndDateBySecurityIds: (startDate: DateTime, endDate: DateTime, securityIds: number[]) => Promise<GetSecurityPrice[]>;
    getMarketHolidays: (endDate: DateTime) => Promise<getUSExchangeHoliday[]>;
    getTradingPostBrokerageAccountsByBrokerage: (userId: string, brokerageName: string) => Promise<TradingPostBrokerageAccountsTable[]>;
    getTradingPostBrokerageAccount: (accountId: number) => Promise<TradingPostBrokerageAccountsTable>;
    getTradingPostBrokerageAccountCurrentHoldingsWithSecurity: (accountId: number) => Promise<TradingPostCurrentHoldingsTableWithSecurity[]>;
    getTradingPostBrokerageWithMostRecentHolding: (tpUserId: string, brokerage: string) => Promise<TradingPostCurrentHoldingsTableWithMostRecentHolding[]>;
    getTradingPostBrokerageAccountCurrentHoldings: (accountId: number) => Promise<TradingPostCurrentHoldingsTable[]>;
    getTradingPostBrokerageAccountTransactions: (accountId: number) => Promise<TradingPostTransactionsTable[]>;
    getTradingPostAccountsWithFinicityNumber: (userId: string) => Promise<TradingPostBrokerageAccountWithFinicity[]>;
    getSecuritiesWithIssue: () => Promise<SecurityIssue[]>;
    getTradingpostCashSecurity: () => Promise<TradingPostCashSecurity[]>;
    upsertInstitutions: (institutions: TradingPostInstitution[]) => Promise<void>;
    upsertInstitution: (institution: TradingPostInstitution) => Promise<number>;
    getInstitutionByName: (name: string) => Promise<TradingPostInstitutionTable | null>;
    getInstitutions: () => Promise<TradingPostInstitutionTable[]>;
    getTradingPostInstitutionsWithFinicityInstitutionId: () => Promise<TradingPostInstitutionWithFinicityInstitutionId[]>;
    getTradingPostInstitutionByFinicityId: (finicityInstitutionId: number) => Promise<TradingPostInstitutionWithFinicityInstitutionId | null>;
    addSecurity: (sec: addSecurity) => Promise<any>;
    upsertFinicityInstitution: (institution: FinicityInstitution) => Promise<number>;
    upsertFinicityInstitutions: (institutions: FinicityInstitution[]) => Promise<void>;
    getFinicityInstitutions: () => Promise<FinicityInstitution[]>;
    getFinicityInstitutionsById: (finicityInstitutionIds: number[]) => Promise<FinicityInstitution[]>;
    getFinicityUser: (userId: string) => Promise<FinicityUser | null>;
    getFinicityUsers: () => Promise<FinicityUser[]>;
    getTradingPostUserByFinicityCustomerId: (finicityCustomerId: string) => Promise<TradingPostUser | null>;
    getFinicityUserByFinicityCustomerId: (customerId: string) => Promise<FinicityUser | null>;
    getFinicityUserByFinicityUserId: (userId: string) => Promise<FinicityUser | null>;
    addFinicityUser: (userId: string, customerId: string, type: string) => Promise<FinicityUser>;
    addFinicityAccount: (account: FinicityAccount) => Promise<FinicityAccount>;
    upsertFinicityAccounts: (accounts: FinicityAccount[]) => Promise<void>;
    getFinicityAccounts: (finicityUserId: number) => Promise<FinicityAccount[]>;
    getFinicityAccountDetails: (finicityUserId: number) => Promise<FinicityAccount[]>;
    upsertFinicityHoldings: (holdings: FinicityHolding[]) => Promise<void>;
    getFinicityHoldings: (finicityUserId: number) => Promise<FinicityHolding[]>;
    upsertFinicityTransactions: (transactions: FinicityTransaction[]) => Promise<void>;
    getFinicityTransactions: (finicityUserId: number) => Promise<FinicityTransaction[]>;
    getTradingPostBrokerageAccounts: (userId: string) => Promise<TradingPostBrokerageAccountsTable[]>;
    addTradingPostBrokerageAccounts: (accounts: TradingPostBrokerageAccounts[]) => Promise<void>;
    upsertTradingPostBrokerageAccounts: (accounts: TradingPostBrokerageAccounts[]) => Promise<number[]>;
    addTradingPostAccountGroups: (accountGroups: TradingPostAccountGroups[]) => Promise<void>;
    deleteTradingPostAccountCurrentHoldings: (accountIds: number[]) => Promise<void>;
    getTradingPostAccountGroups: (userId: string) => Promise<TradingPostAccountGroups[]>;
    addTradingPostAccountGroup: (userId: string, name: string, accountIds: number[], defaultBenchmarkId: number) => Promise<number>;
    upsertTradingPostCurrentHoldings: (currentHoldings: TradingPostCurrentHoldings[]) => Promise<void>;
    addTradingPostHistoricalHoldings: (historicalHoldings: TradingPostHistoricalHoldings[]) => Promise<void>;
    upsertTradingPostHistoricalHoldings: (historicalHoldings: TradingPostHistoricalHoldings[]) => Promise<void>;
    addTradingPostCustomIndustries: (customIndustries: TradingPostCustomIndustry[]) => Promise<void>;
    addTradingPostTransactions: (transactions: TradingPostTransactions[]) => Promise<void>;
    getOldestTransaction: (accountId: number) => Promise<TradingPostTransactions | null>;
    upsertTradingPostTransactions: (transactions: TradingPostTransactions[]) => Promise<void>;
    addTradingPostAccountGroupStats: (groupStats: TradingPostAccountGroupStats[]) => Promise<void>;
    addTradingPostAccountToAccountGroup: (accountToAccountGroups: TradingPostAccountToAccountGroup[]) => Promise<void>;
    getTradingPostHoldingsByAccount: (userId: string, accountId: number, startDate: DateTime, endDate: DateTime) => Promise<HistoricalHoldings[]>;
    getTradingPostHoldingsByAccountGroup: (userId: string, accountGroupId: number, startDate: DateTime, endDate?: DateTime) => Promise<HistoricalHoldings[]>;
    getTradingPostCurrentHoldingsByAccountGroup: (accountGroupId: number) => Promise<HistoricalHoldings[]>;
    getTradingPostTransactionsByAccountGroup: (accountGroupId: number, paging: {
        limit: number;
        offset: number;
    } | undefined, cash?: boolean) => Promise<TradingPostTransactionsByAccountGroup[]>;
    getTradingPostAccountGroupReturns: (accountGroupId: number, startDate: DateTime, endDate: DateTime) => Promise<AccountGroupHPRsTable[]>;
    getDailySecurityPrices: (securityId: number, startDate: DateTime, endDate: DateTime) => Promise<SecurityPrices[]>;
    addSecurities: (securities: addSecurity[]) => Promise<void>;
    getSecuritiesBySymbol: (symbols: string[]) => Promise<GetSecurityBySymbol[]>;
    getSecurities: (securityIds: number[]) => Promise<GetSecurityBySymbol[]>;
    getAccountGroupHPRsLatestDate: (accountGroupId: number) => Promise<any>;
    addAccountGroupReturns: (accountGroupReturns: AccountGroupHPRs[]) => Promise<number>;
    addBenchmarkReturns: (benchmarkReturns: SecurityHPRs[]) => Promise<number>;
    addAccountGroupSummary: (accountGroupSummary: TradingPostAccountGroupStats) => Promise<number>;
    getAccountGroupSummary: (accountGroupId: number) => Promise<TradingPostAccountGroupStats>;
    deleteFinicityHoldings: (accountIds: number[]) => Promise<void>;
    deleteFinicityTransactions: (accountIds: number[]) => Promise<void>;
    deleteFinicityAccounts: (accountIds: number[]) => Promise<void>;
    deleteTradingPostBrokerageAccounts: (accountIds: number[]) => Promise<void>;
    addOptionContract: (optionContract: OptionContract) => Promise<number>;
    upsertOptionContracts: (optionContracts: OptionContract[]) => Promise<void>;
    upsertOptionContract: (oc: OptionContract) => Promise<number | null>;
    getOptionContract: (securityId: number, expirationDate: DateTime, strikePrice: number, optionType: string) => Promise<OptionContractTable | null>;
    getOptionContractsByExternalIds: (externalIds: string[]) => Promise<OptionContractTable[]>;
    getAccountOptionsContractsByTransactions: (accountId: number, securityId: number, strikePrice: number) => Promise<OptionContractTable[]>;
    getTradingPostBrokerageAccountsByBrokerageAndIds: (userId: string, brokerage: string, brokerageAccountIds: string[]) => Promise<TradingPostBrokerageAccountsTable[]>;
    getPendingJobs: (brokerage: string) => Promise<any[]>;
    getBrokerageJobsPerUser: (brokerage: string, brokerageUserId: string) => Promise<any[]>;
    updateJobStatus: (jobId: number, status: any) => Promise<void>;
    getIbkrMasterAndSubAccounts: (accountId: string) => Promise<IbkrAccountTable[]>;
    getIbkrAccount: (accountId: string) => Promise<IbkrAccountTable | null>;
    upsertIbkrAccounts: (accounts: IbkrAccount[]) => Promise<void>;
    upsertIbkrSecurities: (securities: IbkrSecurity[]) => Promise<void>;
    upsertIbkrActivity: (activities: IbkrActivity[]) => Promise<void>;
    upsertIbkrCashReport: (cashReports: IbkrCashReport[]) => Promise<void>;
    upsertIbkrNav: (navs: IbkrNav[]) => Promise<void>;
    upsertIbkrPls: (pls: IbkrPl[]) => Promise<void>;
    upsertIbkrPositions: (positions: IbkrPosition[]) => Promise<void>;
    upsertRobinhoodUsers: (users: RobinhoodUser[]) => Promise<void>;
    getRobinhoodUsers: () => Promise<RobinhoodUserTable[]>;
    getRobinhoodUser: (userId: string) => Promise<RobinhoodUserTable | null>;
    updateRobinhoodUser: (user: RobinhoodUser) => Promise<void>;
    insertRobinhoodUser: (user: RobinhoodUser) => Promise<void>;
    deleteRobinhoodAccountsPositions: (accountIds: number[]) => Promise<void>;
    getRobinhoodAccountsByRobinhoodUserId: (userId: number) => Promise<RobinhoodAccountTable[]>;
    upsertRobinhoodAccounts: (accs: RobinhoodAccount[]) => Promise<void>;
    upsertRobinhoodInstruments: (instruments: RobinhoodInstrument[]) => Promise<void>;
    addRobinhoodInstrument: (instrument: RobinhoodInstrument) => Promise<number>;
    upsertRobinhoodTransactions: (txs: RobinhoodTransaction[]) => Promise<void>;
    upsertRobinhoodOptions: (options: RobinhoodOption[]) => Promise<void>;
    upsertRobinhoodOption: (option: RobinhoodOption) => Promise<number | null>;
    upsertRobinhoodPositions: (positions: RobinhoodPosition[]) => Promise<void>;
    getRobinhoodInstrumentsByExternalId: (instrumentIds: string[]) => Promise<RobinhoodInstrumentTable[]>;
    getRobinhoodInstrumentBySymbol: (symbol: string) => Promise<RobinhoodInstrumentTable | null>;
    getSecurityWithLatestPricingWithRobinhoodIds: (rhIds: number[]) => Promise<SecurityTableWithLatestPriceRobinhoodId[]>;
    getTradingPostOptionsWithRobinhoodOptionIds: (rhOptionIds: number[]) => Promise<OptionContractTableWithRobinhoodId[]>;
    getRobinhoodOptionsByExternalIds: (externalIds: string[]) => Promise<RobinhoodOptionTable[]>;
    getRobinhoodOption: (internalOptionId: number) => Promise<RobinhoodOptionTable | null>;
    upsertBrokerageTasks: (tasks: BrokerageTask[]) => Promise<void>;
    updateTask: (taskId: number, params: {
        userId?: string;
        brokerage?: string;
        type?: BrokerageTaskType;
        date?: DateTime;
        brokerageUserId?: string;
        started?: DateTime;
        finished?: DateTime;
        status?: BrokerageTaskStatusType;
        error?: any;
        data?: any;
    }) => Promise<void>;
    getBrokerageTasks: (params: {
        brokerage?: string;
        userId?: string;
        status?: BrokerageTaskStatusType;
    }) => Promise<BrokerageTaskTable[]>;
    getPendingBrokerageTask: () => Promise<BrokerageTaskTable | null>;
    getExistingTaskByDate: (brokerage: DirectBrokeragesType, type: BrokerageTaskType, date: DateTime, userId: string, brokerageUserId: string) => Promise<BrokerageTaskTable | null>;
    getExistingTask: (brokerage: DirectBrokeragesType, status: BrokerageTaskStatusType, type: BrokerageTaskType, date: DateTime, userId: string, brokerageUserId: string) => Promise<BrokerageTaskTable | null>;
    scheduleTradingPostAccountForDeletion: (accountId: number) => Promise<void>;
}
