INSERT INTO tradingpost_institution (external_id, name, account_type_description, phone, url_home_app, url_logon_app,
                                     oauth_enabled, url_forgot_password, url_online_registration, class, address_city,
                                     address_state, address_country, address_postal_code, address_address_line_1, email,
                                     status)
VALUES ('', 'Robinhood', 'Brokerage', '', 'https://robinhood.com/', 'https://robinhood.com/', true,
        'https://robinhood.com/forgot_password', 'https://robinhood.com/signup', 'Brokerage', 'Menlo Park',
        'California', 'United States', '94025', '85 Willow Road Menlo Park', '', 'online');

CREATE TABLE robinhood_user
(
    id            BIGSERIAL                      NOT NULL,
    user_id       uuid REFERENCES data_user (id) NOT NULL,
    username      text                           NOT NULL UNIQUE,
    device_token  text                           NOT NULL,
    status        text                           NOT NULL,
    uses_mfa      boolean                        NOT NULL,
    access_token  text,
    refresh_token text,
    updated_at    TIMESTAMPTZ                    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at    TIMESTAMPTZ                    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- TODO: Finish allocating additional fields for robinhood account
CREATE TABLE robinhood_account
(
    id                                       BIGSERIAL                             NOT NULL,
    user_id                                  BIGINT REFERENCES robinhood_user (id) NOT NULL,
    account_number                           TEXT                                  NOT NULL UNIQUE,
    url                                      TEXT,
    portfolio_cash                           TEXT,
    can_downgrade_to_cash_url                TEXT,
    user_url                                 TEXT,
    type                                     TEXT,
    brokerage_account_type                   TEXT,
    external_created_at                      TEXT,
    external_updated_at                      TEXT,
    deactivated                              BOOLEAN,
    deposit_halted                           BOOLEAN,
    withdrawl_halted                         BOOLEAN,
    only_position_closing_trades             BOOLEAN,
    buying_power                             TEXT,
    onbp                                     TEXT,
    cash_available_for_withdrawl             TEXT,
    cash                                     TEXT,
    amount_eligible_for_deposit_cancellation TEXT,
    cash_held_for_orders                     TEXT,
    uncleared_deposits                       TEXT,
    sma                                      TEXT,
    sma_held_for_orders                      TEXT,
    unsettled_funds                          TEXT,
    unsettled_debit                          TEXT,
    crypto_buying_power                      TEXT,
    max_ach_early_access_amount              TEXT,
    cash_balances                            TEXT,
    updated_at                               TIMESTAMPTZ                           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at                               TIMESTAMPTZ                           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE robinhood_instrument
(
    id                                    BIGSERIAL   NOT NULL,
    external_id                           TEXT        NOT NULL,
    url                                   TEXT        NOT NULL,
    symbol                                TEXT        NOT NULL UNIQUE,
    quote_url                             TEXT,
    fundamentals_url                      TEXT,
    splits_url                            TEXT,
    state                                 TEXT,
    market_url                            TEXT,
    name                                  TEXT,
    tradeable                             BOOLEAN,
    tradability                           TEXT,
    bloomberg_unique                      TEXT,
    margin_initial_ratio                  TEXT,
    maintenance_ratio                     TEXT,
    country                               TEXT,
    day_trade_ratio                       TEXT,
    list_date                             TEXT,
    min_tick_size                         TEXT,
    type                                  TEXT,
    tradeable_chain_id                    TEXT,
    rhs_tradability                       TEXT,
    fractional_tradability                TEXT,
    default_collar_fraction               TEXT,
    ipo_access_status                     TEXT,
    ipo_access_cob_deadline               TEXT,
    ipo_s1_url                            TEXT,
    ipo_roadshow_url                      TEXT,
    is_spac                               BOOLEAN,
    is_test                               BOOLEAN,
    ipo_access_supports_dsp               BOOLEAN,
    extended_hours_fractional_tradability BOOLEAN,
    internal_halt_reason                  TEXT,
    internal_halt_details                 TEXT,
    internal_halt_sessions                TEXT,
    internal_halt_start_time              TEXT,
    internal_halt_end_time                TEXT,
    internal_halt_source                  TEXT,
    all_day_tradability                   TEXT,
    updated_at                            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at                            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE robinhood_option
(
    id                     BIGSERIAL                                   NOT NULL,
    internal_instrument_id BIGINT REFERENCES robinhood_instrument (id) NOT NULL,
    external_id            TEXT                                        NOT NULL UNIQUE,
    chain_id               TEXT,
    chain_symbol           TEXT,
    external_created_at    TEXT,
    expiration_date        TIMESTAMPTZ                                 NOT NULL,
    issue_date             TEXT,
    min_ticks_above_tick   TEXT,
    min_ticks_below_tick   TEXT,
    min_ticks_cutoff_price TEXT,
    rhs_tradability        TEXT,
    state                  TEXT,
    strike_price           DECIMAL(24, 4)                              NOT NULL,
    tradability            TEXT,
    type                   TEXT                                        NOT NULL,
    external_updated_at    TEXT,
    url                    TEXT,
    sellout_date_time      TEXT,
    long_strategy_code     TEXT,
    short_strategy_code    TEXT,
    updated_at             TIMESTAMPTZ                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at             TIMESTAMPTZ                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX robinhood_option_uniq_idx ON robinhood_option (expiration_date, strike_price, type);

CREATE TABLE robinhood_position
(
    id                            BIGSERIAL                                   NOT NULL,
    internal_account_id           BIGINT REFERENCES robinhood_account (id)    NOT NULL,
    internal_instrument_id        BIGINT REFERENCES robinhood_instrument (id) NOT NULL,
    internal_option_id            BIGINT REFERENCES robinhood_option (id),
    url                           TEXT                                        NOT NULL,
    instrument_url                TEXT,
    instrument_id                 TEXT,
    account_url                   TEXT,
    account_number                TEXT,
    average_buy_price             TEXT,
    pending_average_buy_price     TEXT,
    quantity                      TEXT,
    intraday_average_buy_price    TEXT,
    intraday_quantity             TEXT,
    shares_available_for_exercise TEXT,
    shares_held_for_buys          TEXT,
    shares_held_for_sells         TEXT,
    shares_held_for_stock_grants  TEXT,
    ipo_allocated_quantity        TEXT,
    ipo_dsp_allocated_quantity    TEXT,
    avg_cost_affected             BOOLEAN,
    avg_cost_affected_reason      TEXT,
    is_primary_account            BOOLEAN,
    external_updated_at           TEXT,
    external_created_at           TEXT,
    average_price                 TEXT,
    chain_id                      TEXT,
    chain_symbol                  TEXT,
    external_id                   TEXT,
    type                          TEXT,
    pending_buy_quantity          TEXT,
    pending_expired_quantity      TEXT,
    pending_excercise_quantity    TEXT,
    pending_assignment_quantity   TEXT,
    pending_sell_quantity         TEXT,
    intraday_average_open_price   TEXT,
    trade_value_multiplier        TEXT,
    external_option_id            TEXT,
    updated_at                    TIMESTAMPTZ                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at                    TIMESTAMPTZ                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX robinhood_position_unique_idx ON robinhood_position (internal_account_id, internal_instrument_id, internal_option_id);

CREATE TABLE robinhood_transaction
(
    id                                   BIGSERIAL                                   NOT NULL,
    internal_account_id                  BIGINT REFERENCES robinhood_account (id)    NOT NULL,
    internal_instrument_id               BIGINT REFERENCES robinhood_instrument (id) NOT NULL,
    internal_option_id                   BIGINT REFERENCES robinhood_option (id),
    external_id                          TEXT                                        NOT NULL,
    ref_id                               TEXT,
    url                                  TEXT,
    account_url                          TEXT,
    position_url                         TEXT,
    cancel                               TEXT,
    instrument                           TEXT,
    instrument_id                        TEXT,
    cumulative_quantity                  TEXT,
    average_price                        TEXT,
    fees                                 TEXT,
    state                                TEXT,
    pending_cancel_open_agent            TEXT,
    type                                 TEXT,
    side                                 TEXT,
    time_in_force                        TEXT,
    trigger                              TEXT,
    price                                TEXT,
    stop_price                           TEXT,
    quantity                             TEXT,
    reject_reason                        TEXT,
    external_created_at                  TEXT,
    external_updated_at                  TEXT,
    last_transaction_at                  TEXT,
    -- This comes back as an array within the transaction from robinhood and we unroll it a single tuple
    executions_price                     TEXT,
    executions_quantity                  TEXT,
    executions_rounded_notional          TEXT,
    executions_settlement_date           TEXT,
    executions_timestamp                 TIMESTAMPTZ                                 NOT NULL,
    executions_id                        TEXT,
    executions_ipo_access_execution_rank TEXT,
    extended_hours                       BOOLEAN,
    market_hours                         TEXT,
    override_dtbp_checks                 BOOLEAN,
    override_day_trade_checks            BOOLEAN,
    response_category                    TEXT,
    stop_triggered_at                    TEXT,
    last_trail_price                     TEXT,
    last_trail_price_updated_at          TEXT,
    last_trail_price_source              TEXT,
    dollar_based_amount                  TEXT,
    total_notional_amount                TEXT,
    total_notional_currency_code         TEXT,
    total_notional_currency_id           TEXT,
    executed_notional_amount             TEXT,
    executed_notional_currency_code      TEXT,
    executed_notional_currency_id        TEXT,
    investment_schedule_id               TEXT,
    is_ipo_access_order                  BOOLEAN,
    ipo_access_cancellation_reason       TEXT,
    ipo_access_lower_collared_price      TEXT,
    ipo_access_upper_collared_price      TEXT,
    ipo_access_upper_price               TEXT,
    ipo_access_lower_price               TEXT,
    is_ipo_access_price_finalized        BOOLEAN,
    is_visible_to_user                   BOOLEAN,
    has_ipo_access_custom_price_limit    BOOLEAN,
    is_primary_account                   BOOLEAN,
    order_form_version                   FLOAT,
    preset_percent_limit                 TEXT,
    order_form_type                      TEXT,
    updated_at                           TIMESTAMP                                   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at                           TIMESTAMP                                   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX robinhood_transaction_unique_idx ON robinhood_transaction (internal_account_id,
                                                                               internal_instrument_id,
                                                                               internal_option_id,
                                                                               executions_timestamp,
                                                                               executions_quantity);

INSERT INTO robinhood_instrument(url, external_id, symbol, name, country)
VALUES ('', 'external-cash', 'CUR:USD', 'Cash', 'United States');